<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Category;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    public function run()
    {
        $products = [
            // Fruits
            [
                'name' => 'Pomme',
                'description' => 'La pomme est un fruit sucré de la famille des roses, riche en vitamines et en fibres.',
                'price' => 15.0,
                'image_url' => 'http://10.0.2.2:8000/img/pomme.jpg',
                'weight' => '500 grammes',
                'rate' => 4.0,
                'category_id' => 2,
                'quantity' => 1000,
            ],
            [
                'name' => 'Banane',
                'description' => 'La banane est un fruit tropical connu pour sa douceur et sa richesse en potassium.',
                'price' => 12.0,
                'image_url' => 'http://10.0.2.2:8000/img/banane.jpeg',
                'weight' => '500 grammes',
                'rate' => 5.0,
                'category_id' => 2,
                'quantity' => 1000,
            ],
            [
                'name' => 'Orange',
                'description' => 'L\'orange est un fruit juteux, sucré et acidulé de la famille des agrumes, riche en vitamine C.',
                'price' => 8.0,
                'image_url' => 'http://10.0.2.2:8000/img/orange.jpg',
                'weight' => '500 grammes',
                'rate' => 3.0,
                'category_id' => 2,
                'quantity' => 1000,
            ],
            [
                'name' => 'Fraise',
                'description' => 'La fraise est un petit fruit rouge délicieusement sucré et aromatique.',
                'price' => 20.0,
                'image_url' => 'http://10.0.2.2:8000/img/fraise.jpg',
                'weight' => '250 grammes',
                'rate' => 4.5,
                'category_id' => 2,
                'quantity' => 1000,
            ],
            [
                'name' => 'Raisin',
                'description' => 'Le raisin est un petit fruit juteux qui pousse en grappes, parfait pour une collation sucrée.',
                'price' => 18.0,
                'image_url' => 'http://10.0.2.2:8000/img/Raisin.jpg',
                'weight' => '500 grammes',
                'rate' => 4.0,
                'category_id' => 2,
                'quantity' => 1000,
            ],
            [
                'name' => 'Mangue',
                'description' => 'La mangue est un fruit tropical exotique à la chair juteuse et sucrée.',
                'price' => 25.0,
                'image_url' => 'http://10.0.2.2:8000/img/mangue.jpg',
                'weight' => '400 grammes',
                'rate' => 4.5,
                'category_id' => 2,
                'quantity' => 1000,
            ],
            [
                'name' => 'Pastèque',
                'description' => 'La pastèque est un gros fruit d\'été rafraîchissant, composé principalement d\'eau et de sucre.',
                'price' => 30.0,
                'image_url' => 'http://10.0.2.2:8000/img/pasteque.jpeg',
                'weight' => '3 kilogrammes',
                'rate' => 4.0,
                'category_id' => 2,
                'quantity' => 1000,
            ],
            [
                'name' => 'Ananas',
                'description' => 'L\'ananas est un fruit tropical à la saveur sucrée et acidulée avec une chair juteuse.',
                'price' => 35.0,
                'image_url' => 'http://10.0.2.2:8000/img/anana.jpg',
                'weight' => '1 kilogramme',
                'rate' => 5.0,
                'category_id' => 2,
                'quantity' => 1000,
            ],
            [
                'name' => 'Kiwi',
                'description' => 'Le kiwi est un petit fruit à la chair verte acidulée et aux petites graines noires, riche en vitamine C.',
                'price' => 22.0,
                'image_url' => 'http://10.0.2.2:8000/img/kiwi.jpg',
                'weight' => '500 grammes',
                'rate' => 4.0,
                'category_id' => 2,
                'quantity' => 1000,
            ],
            [
                'name' => 'Cerise',
                'description' => 'La cerise est un petit fruit rouge à noyau, à la chair sucrée et juteuse.',
                'price' => 40.0,
                'image_url' => 'http://10.0.2.2:8000/img/cerise.jpg',
                'weight' => '500 grammes',
                'rate' => 4.5,
                'category_id' => 2,
                'quantity' => 1000,
            ],
    
            // Légumes
            [
                'name' => 'Carotte',
                'description' => 'La carotte est un légume racine de couleur orange, croquant et légèrement sucré.',
                'price' => 6.0,
                'image_url' => 'http://10.0.2.2:8000/img/carotte.jpg',
                'weight' => '500 grammes',
                'rate' => 4.0,
                'category_id' => 3,
                'quantity' => 1000,
            ],
            [
                'name' => 'Tomate',
                'description' => 'La tomate est un fruit rouge et juteux souvent utilisé comme légume en cuisine.',
                'price' => 8.0,
                'image_url' => 'http://10.0.2.2:8000/img/tomate.jpg',
                'weight' => '500 grammes',
                'rate' => 5.0,
                'category_id' => 3,
                'quantity' => 1000,
            ],
            [
                'name' => 'Pomme de terre',
                'description' => 'La pomme de terre est un légume féculent polyvalent utilisé dans de nombreux plats.',
                'price' => 5.0,
                'image_url' => 'http://10.0.2.2:8000/img/pommedeterre.jpg',
                'weight' => '1 kilogramme',
                'rate' => 3.0,
                'category_id' => 3,
                'quantity' => 1000,
            ],
            [
                'name' => 'Oignon',
                'description' => 'L\'oignon est un légume bulbeux au goût prononcé, base de nombreuses recettes.',
                'price' => 7.0,
                'image_url' => 'http://10.0.2.2:8000/img/oignon.jpg',
                'weight' => '500 grammes',
                'rate' => 4.0,
                'category_id' => 3,
                'quantity' => 1000,
            ],
            [
                'name' => 'Laitue',
                'description' => 'La laitue est un légume feuille frais et croquant, parfait pour les salades.',
                'price' => 6.0,
                'image_url' => 'http://10.0.2.2:8000/img/laitue.jpg',
                'weight' => '250 grammes',
                'rate' => 4.0,
                'category_id' => 3,
                'quantity' => 1000,
            ],
            [
                'name' => 'Concombre',
                'description' => 'Le concombre est un légume rafraîchissant à forte teneur en eau avec une saveur légère.',
                'price' => 5.0,
                'image_url' => 'http://10.0.2.2:8000/img/concombre.jpg',
                'weight' => '300 grammes',
                'rate' => 4.0,
                'category_id' => 3,
                'quantity' => 1000,
            ],
            [
                'name' => 'Courgette',
                'description' => 'La courgette est un légume d\'été polyvalent à la chair tendre et à la saveur douce.',
                'price' => 7.0,
                'image_url' => 'http://10.0.2.2:8000/img/courgette.png',
                'weight' => '500 grammes',
                'rate' => 4.0,
                'category_id' => 3,
                'quantity' => 1000,
            ],
            [
                'name' => 'Épinard',
                'description' => 'L\'épinard est un légume feuille vert foncé, riche en fer et en vitamines.',
                'price' => 10.0,
                'image_url' => 'http://10.0.2.2:8000/img/epinard.jpg',
                'weight' => '250 grammes',
                'rate' => 4.0,
                'category_id' => 3,
                'quantity' => 1000,
            ],
            [
                'name' => 'Brocoli',
                'description' => 'Le brocoli est un légume vert de la famille des choux, riche en nutriments.',
                'price' => 12.0,
                'image_url' => 'http://10.0.2.2:8000/img/brocoli.jpg',
                'weight' => '500 grammes',
                'rate' => 4.0,
                'category_id' => 3,
                'quantity' => 1000,
            ],
            [
                'name' => 'Poivron',
                'description' => 'Le poivron est un légume coloré et croquant avec une saveur douce et légèrement sucrée.',
                'price' => 10.0,
                'image_url' => 'http://10.0.2.2:8000/img/poivron.jpg',
                'weight' => '500 grammes',
                'rate' => 4.0,
                'category_id' => 3,
                'quantity' => 1000,
            ],
    
            // Produits laitiers
            [
                'name' => 'Lait',
                'description' => 'Le lait est un produit laitier riche en calcium et en vitamines, base de nombreux produits.',
                'price' => 8.0,
                'image_url' => 'http://10.0.2.2:8000/img/lait.jpg',
                'weight' => '1 litre',
                'rate' => 4.0,
                'category_id' => 4,
                'quantity' => 1000,
            ],
            [
                'name' => 'Yaourt',
                'description' => 'Le yaourt est un produit laitier fermenté, crémeux et légèrement acidulé.',
                'price' => 10.0,
                'image_url' => 'http://10.0.2.2:8000/img/yaourt.jpg',
                'weight' => '500 grammes',
                'rate' => 5.0,
                'category_id' => 4,
                'quantity' => 1000,
            ],
            [
                'name' => 'Fromage',
                'description' => 'Le fromage est un produit laitier fermenté disponible dans une grande variété de saveurs et de textures.',
                'price' => 40.0,
                'image_url' => 'http://10.0.2.2:8000/img/fromage.jpg',
                'weight' => '200 grammes',
                'rate' => 5.0,
                'category_id' => 4,
                'quantity' => 1000,
            ],
            [
                'name' => 'Beurre',
                'description' => 'Le beurre est un produit laitier gras fabriqué à partir de crème barattée.',
                'price' => 18.0,
                'image_url' => 'http://10.0.2.2:8000/img/beurre.jpg',
                'weight' => '250 grammes',
                'rate' => 5.0,
                'category_id' => 4,
                'quantity' => 1000,
            ],
            [
                'name' => 'Crème fraîche',
                'description' => 'La crème fraîche est un produit laitier épais et onctueux utilisé en cuisine et pâtisserie.',
                'price' => 25.0,
                'image_url' => 'http://10.0.2.2:8000/img/Cremefreche.jpg',
                'weight' => '200 grammes',
                'rate' => 4.0,
                'category_id' => 4,
                'quantity' => 1000,
            ],
            [
                'name' => 'Lait concentré',
                'description' => 'Le lait concentré est un produit laitier épaissi par évaporation partielle de l\'eau du lait.',
                'price' => 20.0,
                'image_url' => 'http://10.0.2.2:8000/img/laitconcenter.jpg',
                'weight' => '400 grammes',
                'rate' => 4.0,
                'category_id' => 4,
                'quantity' => 1000,
            ],
            [
                'name' => 'Lait fermenté',
                'description' => 'Le lait fermenté (kéfir) est un produit laitier probiotique à la texture légèrement épaisse.',
                'price' => 15.0,
                'image_url' => 'http://10.0.2.2:8000/img/laitermeter.jpg',
                'weight' => '500 grammes',
                'rate' => 4.0,
                'category_id' => 4,
                'quantity' => 1000,
            ],
            [
                'name' => 'Petit suisse',
                'description' => 'Le petit suisse est un fromage frais onctueux et légèrement acidulé.',
                'price' => 30.0,
                'image_url' => 'http://10.0.2.2:8000/img/petitsuisse.jpg',
                'weight' => '200 grammes',
                'rate' => 4.0,
                'category_id' => 4,
                'quantity' => 1000,
            ],
            [
                'name' => 'Fromage blanc',
                'description' => 'Le fromage blanc est un produit laitier frais, doux et crémeux.',
                'price' => 22.0,
                'image_url' => 'http://10.0.2.2:8000/img/fromageblanc.jpg',
                'weight' => '500 grammes',
                'rate' => 4.0,
                'category_id' => 4,
                'quantity' => 1000,
            ],
            [
                'name' => 'Ricotta',
                'description' => 'La ricotta est un fromage frais italien à la texture douce et crémeuse.',
                'price' => 35.0,
                'image_url' => 'http://10.0.2.2:8000/img/ricotta.jpg',
                'weight' => '250 grammes',
                'rate' => 4.0,
                'category_id' => 4,
                'quantity' => 1000,
            ],
    
            // Viandes
            [
                'name' => 'Poulet',
                'description' => 'Le poulet est une viande blanche polyvalente, maigre et riche en protéines.',
                'price' => 45.0,
                'image_url' => 'http://10.0.2.2:8000/img/poulet.jpg',
                'weight' => '1 kilogramme',
                'rate' => 5.0,
                'category_id' => 5,
                'quantity' => 1000,
            ],
            [
                'name' => 'Bœuf',
                'description' => 'Le bœuf est une viande rouge tendre et savoureuse, riche en fer et en protéines.',
                'price' => 120.0,
                'image_url' => 'http://10.0.2.2:8000/img/boeuf.jpg',
                'weight' => '500 grammes',
                'rate' => 5.0,
                'category_id' => 5,
                'quantity' => 1000,
            ],
            [
                'name' => 'Mouton',
                'description' => 'Le mouton est une viande rouge au goût prononcé, appréciée dans de nombreuses cultures.',
                'price' => 130.0,
                'image_url' => 'http://10.0.2.2:8000/img/mouton.jpg',
                'weight' => '500 grammes',
                'rate' => 4.0,
                'category_id' => 5,
                'quantity' => 1000,
            ],
            [
                'name' => 'Agneau',
                'description' => 'L\'agneau est une viande tendre et délicate provenant de jeunes moutons.',
                'price' => 140.0,
                'image_url' => 'http://10.0.2.2:8000/img/agneau.jpg',
                'weight' => '500 grammes',
                'rate' => 4.0,
                'category_id' => 5,
                'quantity' => 1000,
            ],
            [
                'name' => 'Porc',
                'description' => 'Le porc est une viande polyvalente utilisée dans de nombreuses préparations culinaires.',
                'price' => 90.0,
                'image_url' => 'http://10.0.2.2:8000/img/porc.jpg',
                'weight' => '500 grammes',
                'rate' => 4.0,
                'category_id' => 5,
                'quantity' => 1000,
            ],
            [
                'name' => 'Dinde',
                'description' => 'La dinde est une viande blanche maigre, alternative au poulet avec moins de matières grasses.',
                'price' => 60.0,
                'image_url' => 'http://10.0.2.2:8000/img/dinde.jpg',
                'weight' => '500 grammes',
                'rate' => 4.0,
                'category_id' => 5,
                'quantity' => 1000,
            ],
            [
                'name' => 'Veau',
                'description' => 'Le veau est une viande tendre et délicate provenant de jeunes bovins.',
                'price' => 150.0,
                'image_url' => 'http://10.0.2.2:8000/img/veau.jpg',
                'weight' => '500 grammes',
                'rate' => 5.0,
                'category_id' => 5,
                'quantity' => 1000,
            ],
            [
                'name' => 'Canard',
                'description' => 'Le canard est une viande savoureuse et juteuse avec une peau croustillante.',
                'price' => 100.0,
                'image_url' => 'http://10.0.2.2:8000/img/canard.jpg',
                'weight' => '500 grammes',
                'rate' => 4.0,
                'category_id' => 5,
                'quantity' => 1000,
            ],
            [
                'name' => 'Lapin',
                'description' => 'Le lapin est une viande blanche maigre à la saveur délicate et légèrement sucrée.',
                'price' => 80.0,
                'image_url' => 'http://10.0.2.2:8000/img/lapin.jpg',
                'weight' => '500 grammes',
                'rate' => 4.0,
                'category_id' => 5,
                'quantity' => 1000,
            ],
            [
                'name' => 'Saucisse',
                'description' => 'La saucisse est un produit de charcuterie à base de viande hachée, assaisonnée et embossée.',
                'price' => 40.0,
                'image_url' => 'http://10.0.2.2:8000/img/saucisse.jpg',
                'weight' => '400 grammes',
                'rate' => 4.0,
                'category_id' => 5,
                'quantity' => 1000,
            ],
        ];
    
        foreach ($products as $product) {
            Product::create($product);
        }
    }
}